name: Bug Report
description: File a bug report
body:
  - type: dropdown
    id: only_immptl
    attributes:
      label: Does the issue ocur with only Immersive Portals mod and Farbic API?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for writing the issue report.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "Describe the issue."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Post the log here
      description: The log is `game_directory/logs/latest.log`
      render: shell
